// <auto-generated />
using System;
using AttentionPlease.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AttentionPlease.EFCore.Migrations
{
    [DbContext(typeof(AttentionPleaseDBContext))]
    partial class AttentionPleaseDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AttentionPlease.Domain.Models.AnniversaryCelebration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Day");

                    b.Property<string>("Description");

                    b.Property<string>("Summary");

                    b.HasKey("Id");

                    b.ToTable("AnniversaryCelebrations");
                });

            modelBuilder.Entity("AttentionPlease.Domain.Models.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d52edcc-09ac-4f5b-8d5d-c00c8c326290"),
                            Name = "Fam Jer"
                        });
                });

            modelBuilder.Entity("AttentionPlease.Domain.Models.CalendarSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CalendarId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("CalendarSubscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
